/** Routes de l'application (front). Toujours passer par ces helpers — jamais de chaînes en dur. */
export const ROUTES = {
  home: "/",
  products: "/produits",
  product: (id: number | string) => `/produits/${id}`,
  category: (id: number | string) => `/categorie/${id}`,
  search: (q?: string) => (q ? `/recherche?q=${encodeURIComponent(q)}` : "/recherche"),
  favorites: "/favoris",
  cart: "/panier",
  checkout: "/commande",
  login: (next?: string) => (next ? `/connexion?next=${encodeURIComponent(next)}` : "/connexion"),
  register: "/inscription",
  profile: "/compte/profil",
  orders: "/compte/commandes",
  messages: "/messages",
  conversation: (id: number | string) => `/messages/${id}`,
  notifications: "/notifications",
  assistant: "/assistant",
  about: "/a-propos",
  contact: "/contact",
  guide: "/guide",

  admin: {
    root: "/admin",
    products: "/admin/produits",
    productNew: "/admin/produits/nouveau",
    product: (id: number | string) => `/admin/produits/${id}`,
    productEdit: (id: number | string) => `/admin/produits/${id}/modifier`,
    sales: "/admin/ventes",
    saleNew: "/admin/ventes/nouvelle",
    saleEdit: (id: number | string) => `/admin/ventes/${id}/modifier`,
    analytics: "/admin/analytique",
    resellers: "/admin/revendeurs",
    orders: "/admin/commandes",
  },
} as const;
