/** Routes de l'application (front). Toujours passer par ces helpers — jamais de chaînes en dur. */
export const ROUTES = {
  home: "/",
  products: "/produits",
  product: (slug: string) => `/produits/${slug}`,
  category: (slug: string) => `/categorie/${slug}`,
  search: (q?: string) => (q ? `/recherche?q=${encodeURIComponent(q)}` : "/recherche"),
  favorites: "/favoris",
  cart: "/panier",
  checkout: "/commande",
  login: (next?: string) => (next ? `/connexion?next=${encodeURIComponent(next)}` : "/connexion"),
  register: "/inscription",
  googleCallback: "/connexion/google",
  verifyEmail: (key: string) => `/verifier-email/${encodeURIComponent(key)}`,
  resetPassword: "/reinitialiser-mot-de-passe",
  profile: "/compte/profil",
  orders: "/compte/commandes",
  messages: "/messages",
  conversation: (id: number | string) => `/messages/${id}`,
  notifications: "/notifications",
  assistant: "/assistant",
  about: "/a-propos",
  contact: "/contact",
  guide: "/guide",
  becomeReseller: "/devenir-revendeur",
  page: (slug: string) => `/pages/${slug}`,
  newsletterUnsubscribe: "/newsletter/desinscription",
  track: "/suivi",
  orderDetail: (number: number | string) => `/compte/commandes/${encodeURIComponent(number)}`,
  addresses: "/compte/adresses",
  settings: "/compte/parametres",

  admin: {
    root: "/admin",
    products: "/admin/produits",
    productNew: "/admin/produits/nouveau",
    product: (id: number | string) => `/admin/produits/${id}`,
    productEdit: (id: number | string) => `/admin/produits/${id}/modifier`,
    sales: "/admin/ventes",
    saleNew: "/admin/ventes/nouvelle",
    saleEdit: (id: number | string) => `/admin/ventes/${id}/modifier`,
    analytics: "/admin/analytique",
    resellers: "/admin/revendeurs",
    orders: "/admin/commandes",
    order: (id: number | string) => `/admin/commandes/${id}`,
    categories: "/admin/categories",
    saleConvert: "/admin/ventes/convertir",
    inbox: "/admin/messages",
    conversation: (id: number | string) => `/admin/messages/${id}`,
    notifications: "/admin/notifications",
    commissions: "/admin/commissions",
    users: "/admin/utilisateurs",
    audit: "/admin/audit",
    invites: "/admin/invites",
  },
} as const;
